parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/34.h, #include <zmk-helpers/key-labels/totem.h>"
  zmk_additional_includes:
    - "modules/helpers/include"

draw_config:
  footer_text: "coryebner/zmk-config"
  dark_mode: auto